services:
  traefik:
    image: "traefik:v3.2"
    networks:
      - passeports-network
    command:
      - "--api.insecure=true"
      - "--providers.docker.network=passeports-network"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.email=paulmerandon@gmail.com"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"  # Interface admin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /letsencrypt:/letsencrypt

  passeports:
    image: passeports-backend
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=docker_external"
      - "traefik.http.routers.passeports.rule=Host(`passportmagician.com`)"
      - "traefik.http.routers.passeports.entrypoints=websecure"
      - "traefik.http.services.passeports.loadbalancer.server.port=8080"  # Port interne du backend
      - "traefik.http.routers.guestbook.tls.certresolver=myresolver"
    build:
      context: .
      dockerfile: passeports-backend/Dockerfile
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    ports: []  # Pas besoin de publier 8080 directement
    secrets:
      - source: db_connection_string
        target: db_connection_string
    environment:
      DB_CONNECTION_FILE: /run/secrets/db_connection_string
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - passeports-network

networks:
  passeports-network:
    driver: overlay
    attachable: true

secrets:
  db_connection_string:
    external: true
