services:
  passeports-backend:
    image: passeports-backend
    build:
      context: .
      dockerfile: passeports-backend/Dockerfile
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    secrets:
      - source: db_connection_string
        target: db_connection_string
    environment:
      DB_CONNECTION_FILE: /run/secrets/db_connection_string
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - passeports-network

networks:
  passeports-network:
    driver: overlay
    attachable: true

secrets:
  db_connection_string:
    external: true